# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and its members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateConnectedOrganizationRequestKybPrefill(BaseModel):
    """
    Optional KYB details to forward for the end client. When provided, these values prefill the end client's onboarding form. Every field is optional.
    """ # noqa: E501
    company_name: Optional[StrictStr] = Field(default=None, description="The registered legal name of the company.", json_schema_extra={"examples": ["Acme Inc"]})
    doing_business_as: Optional[StrictStr] = Field(default=None, description="The trade name (DBA) the company operates under, if different from its legal name.", json_schema_extra={"examples": ["Acme"]})
    company_structure: Optional[StrictStr] = Field(default=None, description="The company's legal entity type. Free-form text; any value is accepted. Common values include `Sole proprietorship`, `Corporation (Inc)`, `Limited liability company (LLC)`, `Limited liability partnership (LLP)`, `Public limited company (PLC)`, and `Private limited company (LTD)`.", json_schema_extra={"examples": ["Corporation (Inc)"]})
    company_registration_number: Optional[StrictStr] = Field(default=None, description="The company's tax ID or registration number.", json_schema_extra={"examples": ["12-3456789"]})
    country_code: Optional[StrictStr] = Field(default=None, description="The ISO 3166-1 alpha-2 country code of the company. Must be a supported country.", json_schema_extra={"examples": ["US"]})
    website_url: Optional[StrictStr] = Field(default=None, description="The company's website URL. Must be a well-formed URL.", json_schema_extra={"examples": ["https://acme.example.com"]})
    address_1: Optional[StrictStr] = Field(default=None, description="The company's street address.", json_schema_extra={"examples": ["123 Main St"]})
    address_2: Optional[StrictStr] = Field(default=None, description="The second line of the company's street address (suite, unit, floor, etc.).", json_schema_extra={"examples": ["Suite 100"]})
    city: Optional[StrictStr] = Field(default=None, description="The company's city.", json_schema_extra={"examples": ["Brooklyn"]})
    state: Optional[StrictStr] = Field(default=None, description="The company's state or province.", json_schema_extra={"examples": ["NY"]})
    postal_code: Optional[StrictStr] = Field(default=None, description="The company's ZIP or postal code.", json_schema_extra={"examples": ["11201"]})
    __properties: ClassVar[List[str]] = ["company_name", "doing_business_as", "company_structure", "company_registration_number", "country_code", "website_url", "address_1", "address_2", "city", "state", "postal_code"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateConnectedOrganizationRequestKybPrefill from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateConnectedOrganizationRequestKybPrefill from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "company_name": obj.get("company_name"),
            "doing_business_as": obj.get("doing_business_as"),
            "company_structure": obj.get("company_structure"),
            "company_registration_number": obj.get("company_registration_number"),
            "country_code": obj.get("country_code"),
            "website_url": obj.get("website_url"),
            "address_1": obj.get("address_1"),
            "address_2": obj.get("address_2"),
            "city": obj.get("city"),
            "state": obj.get("state"),
            "postal_code": obj.get("postal_code")
        })
        return _obj


