# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and its members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateConnectedOrganizationMemberRequest(BaseModel):
    """
    CreateConnectedOrganizationMemberRequest
    """ # noqa: E501
    connected_organization_id: StrictStr = Field(description="The ID of the connected organization.")
    external_name: Optional[StrictStr] = Field(default=None, description="The name associated with the user in your systems.", json_schema_extra={"examples": ["Jane Doe"]})
    external_email: Optional[StrictStr] = Field(default=None, description="The email associated with the user in your systems.", json_schema_extra={"examples": ["jane@doe.com"]})
    role: Optional[StrictStr] = Field(default=None, description="The role ID to assign to the member within the organization. Only applicable when the connected organization is already linked to an existing Tremendous organization. ", json_schema_extra={"examples": ["ADMIN"]})
    __properties: ClassVar[List[str]] = ["connected_organization_id", "external_name", "external_email", "role"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateConnectedOrganizationMemberRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateConnectedOrganizationMemberRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "connected_organization_id": obj.get("connected_organization_id"),
            "external_name": obj.get("external_name"),
            "external_email": obj.get("external_email"),
            "role": obj.get("role")
        })
        return _obj


