# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and its members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CurrencyCodes(str, Enum):
    """
    CurrencyCodes
    """

    """
    allowed enum values
    """
    USD = 'USD'
    CAD = 'CAD'
    EUR = 'EUR'
    AED = 'AED'
    AFN = 'AFN'
    ALL = 'ALL'
    AMD = 'AMD'
    ARS = 'ARS'
    AUD = 'AUD'
    AZN = 'AZN'
    BAM = 'BAM'
    BDT = 'BDT'
    BGN = 'BGN'
    BHD = 'BHD'
    BIF = 'BIF'
    BND = 'BND'
    BOB = 'BOB'
    BRL = 'BRL'
    BWP = 'BWP'
    BYR = 'BYR'
    BZD = 'BZD'
    CDF = 'CDF'
    CHF = 'CHF'
    CLP = 'CLP'
    CNY = 'CNY'
    COP = 'COP'
    CRC = 'CRC'
    CVE = 'CVE'
    CZK = 'CZK'
    DJF = 'DJF'
    DKK = 'DKK'
    DOP = 'DOP'
    DZD = 'DZD'
    EEK = 'EEK'
    EGP = 'EGP'
    ERN = 'ERN'
    ETB = 'ETB'
    GBP = 'GBP'
    GEL = 'GEL'
    GHS = 'GHS'
    GNF = 'GNF'
    GTQ = 'GTQ'
    HKD = 'HKD'
    HNL = 'HNL'
    HRK = 'HRK'
    HUF = 'HUF'
    IDR = 'IDR'
    ILS = 'ILS'
    INR = 'INR'
    IQD = 'IQD'
    IRR = 'IRR'
    ISK = 'ISK'
    JMD = 'JMD'
    JOD = 'JOD'
    JPY = 'JPY'
    KES = 'KES'
    KHR = 'KHR'
    KRW = 'KRW'
    KWD = 'KWD'
    KZT = 'KZT'
    LBP = 'LBP'
    LKR = 'LKR'
    LTL = 'LTL'
    LVL = 'LVL'
    MAD = 'MAD'
    MDL = 'MDL'
    MGA = 'MGA'
    MKD = 'MKD'
    MMK = 'MMK'
    MOP = 'MOP'
    MUR = 'MUR'
    MXN = 'MXN'
    MYR = 'MYR'
    MZN = 'MZN'
    NAD = 'NAD'
    NGN = 'NGN'
    NIO = 'NIO'
    NOK = 'NOK'
    NPR = 'NPR'
    NZD = 'NZD'
    OMR = 'OMR'
    PAB = 'PAB'
    PEN = 'PEN'
    PHP = 'PHP'
    PKR = 'PKR'
    PLN = 'PLN'
    PYG = 'PYG'
    QAR = 'QAR'
    RON = 'RON'
    RSD = 'RSD'
    RUB = 'RUB'
    RWF = 'RWF'
    SAR = 'SAR'
    SDG = 'SDG'
    SEK = 'SEK'
    SGD = 'SGD'
    SOS = 'SOS'
    SYP = 'SYP'
    THB = 'THB'
    TND = 'TND'
    TOP = 'TOP'
    TRY = 'TRY'
    TTD = 'TTD'
    TWD = 'TWD'
    TZS = 'TZS'
    UAH = 'UAH'
    UGX = 'UGX'
    UYU = 'UYU'
    UZS = 'UZS'
    VEF = 'VEF'
    VND = 'VND'
    XAF = 'XAF'
    XOF = 'XOF'
    YER = 'YER'
    ZAR = 'ZAR'
    ZMK = 'ZMK'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CurrencyCodes from a JSON string"""
        return cls(json.loads(json_str))


